language: python
python:
  - "3.7"

install:
  - pip install numpy pyrecorder
  - python setup.py build_ext --inplace
  - python setup.py sdist
  - pip install dist/*.tar.gz


script:
  - cd tests
  - python test_suite.py
